### ISSUE TITLE
Swift 2 version?

### ISSUE THREAD

**Issue by eeschimosu** [entotsu/TKSwarmAlert#2]
Do you have by any chance a swift 2 version?

**Comment by a11enwong** [comment]
Do you have by any chance a swift 2 version?

**Comment by entotsu** [comment]
Sorry, Please Convert and PullRequest...! :sweat_smile:

**Comment by darvs** [comment]
I have just submitted a Pull Request for Swift 2 support with Xcode 7. 

It works fine for me, if you try it out please let me know how it works for you, @eeschimosu and @a11enwong .

**Comment by entotsu** [comment]
Thanks!!

I merged it!!

**Comment by darvs** [comment]
Swift 2.1 and Xcode 7.1 just came out. I just installed those... and of course there was another tiny modification needed. I just sent an additional Pull Request for that one too.

**Comment by entotsu** [comment]
Thanks!!!!!!!!!!!! :pray:
